/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MouseHoverRating {
    'maxValue': number;
    'value': number;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyRatingComponent {
    'maxValue': number;
    'value': number;
  }
}

declare global {


  interface HTMLMouseHoverRatingElement extends Components.MouseHoverRating, HTMLStencilElement {}
  var HTMLMouseHoverRatingElement: {
    prototype: HTMLMouseHoverRatingElement;
    new (): HTMLMouseHoverRatingElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLMyRatingComponentElement extends Components.MyRatingComponent, HTMLStencilElement {}
  var HTMLMyRatingComponentElement: {
    prototype: HTMLMyRatingComponentElement;
    new (): HTMLMyRatingComponentElement;
  };
  interface HTMLElementTagNameMap {
    'mouse-hover-rating': HTMLMouseHoverRatingElement;
    'my-component': HTMLMyComponentElement;
    'my-rating-component': HTMLMyRatingComponentElement;
  }
}

declare namespace LocalJSX {
  interface MouseHoverRating {
    'maxValue'?: number;
    'value'?: number;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface MyRatingComponent {
    'maxValue'?: number;
    'value'?: number;
  }

  interface IntrinsicElements {
    'mouse-hover-rating': MouseHoverRating;
    'my-component': MyComponent;
    'my-rating-component': MyRatingComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'mouse-hover-rating': LocalJSX.MouseHoverRating & JSXBase.HTMLAttributes<HTMLMouseHoverRatingElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'my-rating-component': LocalJSX.MyRatingComponent & JSXBase.HTMLAttributes<HTMLMyRatingComponentElement>;
    }
  }
}


